import { PDFDocument } from 'pdf-lib'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

async function main() {
  const buf = await readFile(path.resolve(__dirname, '../public/forms/BIR-2307-fillable.pdf'))
  const doc = await PDFDocument.load(buf)
  const fields = doc.getForm().getFields().map(f => ({
    name: f.getName(),
    type: f.constructor.name,
  }))
  const output = `// AUTO-GENERATED by scripts/extract-2307-fields.ts\n` +
                 `export interface Bir2307Fields {\n` +
                 fields.map(f => `  ${JSON.stringify(f.name)}: ${tsTypeFor(f.type)}`).join('\n') +
                 `\n}\n\n` +
                 `export const BIR_2307_FIELD_NAMES = ${JSON.stringify(fields.map(f => f.name), null, 2)} as const\n`
  await writeFile(path.resolve(__dirname, '../src/lib/cwt/pdf-fields.ts'), output)
  console.log(`Extracted ${fields.length} fields`)
}

function tsTypeFor(type: string): string {
  if (type.includes('CheckBox') || type.includes('RadioGroup')) return 'boolean'
  return 'string'
}

main().catch(e => { console.error(e); process.exit(1) })
